# Generated by Django 5.2.3 on 2025-06-22 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配通知"),
                            ("task_status_changed", "任务状态变更"),
                            ("task_due_reminder", "任务截止提醒"),
                            ("task_comment_mention", "任务评论@提及"),
                            ("team_invitation", "团队邀请"),
                            ("board_member_added", "看板成员添加"),
                            ("daily_summary", "每日工作摘要"),
                            ("weekly_summary", "每周工作摘要"),
                            ("team_activity_summary", "团队活动摘要"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        help_text="支持Django模板语法",
                        max_length=200,
                        verbose_name="邮件主题模板",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="支持Django模板语法，支持HTML",
                        verbose_name="邮件正文模板",
                    ),
                ),
                ("is_html", models.BooleanField(default=True, verbose_name="HTML格式")),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮件模板",
                "verbose_name_plural": "邮件模板",
                "db_table": "notifications_email_template",
            },
        ),
        migrations.CreateModel(
            name="NotificationQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="队列名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "queue_type",
                    models.CharField(
                        default="email", max_length=30, verbose_name="队列类型"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配通知"),
                            ("task_status_changed", "任务状态变更"),
                            ("task_due_reminder", "任务截止提醒"),
                            ("task_comment_mention", "任务评论@提及"),
                            ("team_invitation", "团队邀请"),
                            ("board_member_added", "看板成员添加"),
                            ("daily_summary", "每日工作摘要"),
                            ("weekly_summary", "每周工作摘要"),
                            ("team_activity_summary", "团队活动摘要"),
                        ],
                        max_length=30,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "处理失败"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="状态",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="计划执行时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="总数"),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(default=0, verbose_name="成功数"),
                ),
                (
                    "failed_count",
                    models.PositiveIntegerField(default=0, verbose_name="失败数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notification_queues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知队列",
                "verbose_name_plural": "通知队列",
                "db_table": "notifications_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnsubscribeToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=64, unique=True, verbose_name="令牌"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("task_assigned", "任务分配通知"),
                            ("task_status_changed", "任务状态变更"),
                            ("task_due_reminder", "任务截止提醒"),
                            ("task_comment_mention", "任务评论@提及"),
                            ("team_invitation", "团队邀请"),
                            ("board_member_added", "看板成员添加"),
                            ("daily_summary", "每日工作摘要"),
                            ("weekly_summary", "每周工作摘要"),
                            ("team_activity_summary", "团队活动摘要"),
                        ],
                        help_text="留空表示全部退订",
                        max_length=30,
                        verbose_name="模板类型",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="已使用")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "退订令牌",
                "verbose_name_plural": "退订令牌",
                "db_table": "notifications_unsubscribe_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_assigned",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="任务分配",
                    ),
                ),
                (
                    "task_status_changed",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="任务状态变更",
                    ),
                ),
                (
                    "task_due_reminder",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="任务截止提醒",
                    ),
                ),
                (
                    "task_comment_mention",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="任务评论@提及",
                    ),
                ),
                (
                    "team_invitation",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="团队邀请",
                    ),
                ),
                (
                    "board_member_added",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="immediate",
                        max_length=10,
                        verbose_name="看板成员添加",
                    ),
                ),
                (
                    "daily_summary",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="每日工作摘要",
                    ),
                ),
                (
                    "weekly_summary",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="每周工作摘要",
                    ),
                ),
                (
                    "team_activity_summary",
                    models.CharField(
                        choices=[
                            ("immediate", "立即通知"),
                            ("daily", "每日摘要"),
                            ("weekly", "每周摘要"),
                            ("never", "不接收"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="团队活动摘要",
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, verbose_name="启用邮件通知"),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="邮箱已验证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户通知偏好",
                "verbose_name_plural": "用户通知偏好",
                "db_table": "notifications_user_preference",
            },
        ),
        migrations.CreateModel(
            name="EmailNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="收件人邮箱"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配通知"),
                            ("task_status_changed", "任务状态变更"),
                            ("task_due_reminder", "任务截止提醒"),
                            ("task_comment_mention", "任务评论@提及"),
                            ("team_invitation", "团队邀请"),
                            ("board_member_added", "看板成员添加"),
                            ("daily_summary", "每日工作摘要"),
                            ("weekly_summary", "每周工作摘要"),
                            ("team_activity_summary", "团队活动摘要"),
                        ],
                        max_length=30,
                        verbose_name="模板类型",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="邮件主题")),
                ("body", models.TextField(verbose_name="邮件正文")),
                ("is_html", models.BooleanField(default=True, verbose_name="HTML格式")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sending", "发送中"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="发送状态",
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="计划发送时间"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际发送时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "related_task_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联任务ID"
                    ),
                ),
                (
                    "related_board_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联看板ID"
                    ),
                ),
                (
                    "related_team_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联团队ID"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "clicked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="点击时间"
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="退订时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收件人",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件通知",
                "verbose_name_plural": "邮件通知",
                "db_table": "notifications_email_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_132b8d_idx",
                    ),
                    models.Index(
                        fields=["template_type", "status"],
                        name="notificatio_templat_6e8adb_idx",
                    ),
                    models.Index(
                        fields=["send_at"], name="notificatio_send_at_c65629_idx"
                    ),
                ],
            },
        ),
    ]
