# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="团队名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="团队描述"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teams/avatars/",
                        verbose_name="团队头像",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="公开团队允许任何人查看",
                        verbose_name="公开团队",
                    ),
                ),
                (
                    "allow_join_request",
                    models.BooleanField(default=True, verbose_name="允许加入申请"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
                "db_table": "teams_team",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "所有者"),
                            ("admin", "管理员"),
                            ("member", "成员"),
                            ("guest", "访客"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="邀请角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("accepted", "已接受"),
                            ("declined", "已拒绝"),
                            ("expired", "已过期"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="邀请消息"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="响应时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "团队邀请",
                "verbose_name_plural": "团队邀请",
                "db_table": "teams_invitation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "所有者"),
                            ("admin", "管理员"),
                            ("member", "成员"),
                            ("guest", "访客"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待确认"),
                            ("active", "活跃"),
                            ("inactive", "非活跃"),
                            ("blocked", "已屏蔽"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "invitation_message",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="邀请消息"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="加入时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "团队成员",
                "verbose_name_plural": "团队成员",
                "db_table": "teams_membership",
                "ordering": ["-created_at"],
            },
        ),
    ]
