# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_teams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="invitee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_team_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="被邀请人",
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_team_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AddField(
            model_name="teaminvitation",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="teams.team",
                verbose_name="团队",
            ),
        ),
        migrations.AddField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teaminvitation",
            unique_together={("team", "invitee", "status")},
        ),
        migrations.AlterUniqueTogether(
            name="teammembership",
            unique_together={("team", "user")},
        ),
    ]
