# Generated by Django 5.2.3 on 2025-06-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="仪表板名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "layout",
                    models.JSONField(blank=True, default=dict, verbose_name="布局配置"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开仪表板"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认仪表板"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, verbose_name="刷新间隔(秒)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "仪表板",
                "verbose_name_plural": "仪表板",
                "db_table": "reports_dashboard",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart_line", "折线图"),
                            ("chart_bar", "柱状图"),
                            ("chart_pie", "饼图"),
                            ("chart_doughnut", "环形图"),
                            ("stats_card", "统计卡片"),
                            ("progress_bar", "进度条"),
                            ("task_list", "任务列表"),
                            ("calendar", "日历"),
                            ("timeline", "时间线"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="部件类型",
                    ),
                ),
                (
                    "position_x",
                    models.PositiveIntegerField(default=0, verbose_name="X坐标"),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(default=0, verbose_name="Y坐标"),
                ),
                ("width", models.PositiveIntegerField(default=4, verbose_name="宽度")),
                ("height", models.PositiveIntegerField(default=3, verbose_name="高度")),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="配置"),
                ),
                (
                    "data_source",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="数据源配置"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="可见")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "仪表板部件",
                "verbose_name_plural": "仪表板部件",
                "db_table": "reports_dashboard_widget",
                "ordering": ["position_y", "position_x"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="报表名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="报表描述"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("task_completion", "任务完成统计"),
                            ("user_workload", "用户工作负载"),
                            ("team_performance", "团队绩效"),
                            ("project_progress", "项目进度"),
                            ("time_tracking", "时间追踪"),
                            ("custom", "自定义报表"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="报表配置"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="筛选条件"),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="定时生成"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "一次性"),
                            ("daily", "每日"),
                            ("weekly", "每周"),
                            ("monthly", "每月"),
                            ("quarterly", "每季度"),
                            ("yearly", "每年"),
                        ],
                        default="once",
                        max_length=15,
                        verbose_name="生成频率",
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次生成时间"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开报表"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="激活状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报表",
                "verbose_name_plural": "报表",
                "db_table": "reports_report",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "执行失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(blank=True, null=True, verbose_name="结果数据"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="文件路径"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, verbose_name="记录数量"),
                ),
                (
                    "execution_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="执行时间(秒)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "报表执行记录",
                "verbose_name_plural": "报表执行记录",
                "db_table": "reports_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="模板描述"),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("task_completion", "任务完成统计"),
                            ("user_workload", "用户工作负载"),
                            ("team_performance", "团队绩效"),
                            ("project_progress", "项目进度"),
                            ("time_tracking", "时间追踪"),
                            ("custom", "自定义报表"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                (
                    "config_template",
                    models.JSONField(default=dict, verbose_name="配置模板"),
                ),
                (
                    "filters_template",
                    models.JSONField(default=dict, verbose_name="筛选模板"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="分类"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用次数"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开模板"),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="系统模板"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报表模板",
                "verbose_name_plural": "报表模板",
                "db_table": "reports_template",
                "ordering": ["-usage_count", "-updated_at"],
            },
        ),
    ]
