# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0002_initial"),
        ("reports", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所有者",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="共享用户",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to="teams.team",
                verbose_name="关联团队",
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="dashboard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="widgets",
                to="reports.dashboard",
                verbose_name="仪表板",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="boards.board",
                verbose_name="关联看板",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="shared_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="共享用户",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="teams.team",
                verbose_name="关联团队",
            ),
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="widgets",
                to="reports.report",
                verbose_name="关联报表",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="reports.report",
                verbose_name="报表",
            ),
        ),
        migrations.AddField(
            model_name="reportexecution",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_executions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="触发人",
            ),
        ),
        migrations.AddField(
            model_name="reporttemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_report_templates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建者",
            ),
        ),
    ]
