# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="看板名称",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=120, unique=True, verbose_name="URL标识"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="看板描述"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#0079bf", max_length=7, verbose_name="背景颜色"
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="boards/backgrounds/",
                        verbose_name="背景图片",
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("kanban", "看板模板"),
                            ("scrum", "敏捷开发"),
                            ("personal", "个人任务"),
                            ("project", "项目管理"),
                            ("custom", "自定义"),
                        ],
                        default="kanban",
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "私有"),
                            ("team", "团队可见"),
                            ("public", "公开"),
                        ],
                        default="private",
                        max_length=10,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="已关闭"),
                ),
                (
                    "enable_calendar",
                    models.BooleanField(default=True, verbose_name="启用日历视图"),
                ),
                (
                    "enable_timeline",
                    models.BooleanField(default=True, verbose_name="启用时间线"),
                ),
                (
                    "enable_comments",
                    models.BooleanField(default=True, verbose_name="启用评论"),
                ),
                (
                    "enable_attachments",
                    models.BooleanField(default=True, verbose_name="启用附件"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "看板",
                "verbose_name_plural": "看板",
                "db_table": "boards_board",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create_board", "创建看板"),
                            ("update_board", "更新看板"),
                            ("add_member", "添加成员"),
                            ("remove_member", "移除成员"),
                            ("create_list", "创建列表"),
                            ("update_list", "更新列表"),
                            ("archive_list", "归档列表"),
                            ("create_task", "创建任务"),
                            ("update_task", "更新任务"),
                            ("move_task", "移动任务"),
                            ("archive_task", "归档任务"),
                            ("add_comment", "添加评论"),
                            ("add_attachment", "添加附件"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="操作描述"),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="目标类型"
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="目标ID"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "看板活动",
                "verbose_name_plural": "看板活动",
                "db_table": "boards_activity",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BoardLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="标签名称")),
                (
                    "color",
                    models.CharField(
                        default="#61bd4f", max_length=7, verbose_name="标签颜色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "看板标签",
                "verbose_name_plural": "看板标签",
                "db_table": "boards_label",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BoardList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="列表名称")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="排序位置"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="颜色标识"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="已归档"),
                ),
                (
                    "is_done_list",
                    models.BooleanField(default=False, verbose_name="完成列表"),
                ),
                (
                    "wip_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="在制品限制"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "看板列表",
                "verbose_name_plural": "看板列表",
                "db_table": "boards_list",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理员"),
                            ("member", "成员"),
                            ("observer", "观察者"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="活跃状态"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "看板成员",
                "verbose_name_plural": "看板成员",
                "db_table": "boards_member",
                "ordering": ["-joined_at"],
            },
        ),
    ]
