# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("boards", "0001_initial"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_boards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所有者",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boards",
                to="teams.team",
                verbose_name="所属团队",
            ),
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="boards.board",
                verbose_name="看板",
            ),
        ),
        migrations.AddField(
            model_name="boardactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="操作用户",
            ),
        ),
        migrations.AddField(
            model_name="boardlabel",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="labels",
                to="boards.board",
                verbose_name="所属看板",
            ),
        ),
        migrations.AddField(
            model_name="boardlist",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to="boards.board",
                verbose_name="所属看板",
            ),
        ),
        migrations.AddField(
            model_name="boardmember",
            name="board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="boards.board",
                verbose_name="看板",
            ),
        ),
        migrations.AddField(
            model_name="boardmember",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="board_invitations_sent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="邀请人",
            ),
        ),
        migrations.AddField(
            model_name="boardmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["owner", "-updated_at"], name="boards_boar_owner_i_4420f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["team", "-updated_at"], name="boards_boar_team_id_e815d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["visibility", "-updated_at"],
                name="boards_boar_visibil_129ea7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="boardactivity",
            index=models.Index(
                fields=["board", "-created_at"], name="boards_acti_board_i_c65638_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardactivity",
            index=models.Index(
                fields=["user", "-created_at"], name="boards_acti_user_id_27b3b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="boardlabel",
            unique_together={("board", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="boardlist",
            unique_together={("board", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="boardmember",
            unique_together={("board", "user")},
        ),
    ]
