# Generated by Django 5.2.3 on 2025-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="default",
                        max_length=100,
                        unique=True,
                        verbose_name="配置名称",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        default="django.core.mail.backends.smtp.EmailBackend",
                        max_length=200,
                        verbose_name="邮件后端",
                    ),
                ),
                ("host", models.CharField(max_length=100, verbose_name="SMTP服务器")),
                ("port", models.IntegerField(default=587, verbose_name="SMTP端口")),
                ("use_tls", models.BooleanField(default=True, verbose_name="使用TLS")),
                ("use_ssl", models.BooleanField(default=False, verbose_name="使用SSL")),
                ("username", models.CharField(max_length=200, verbose_name="用户名")),
                ("password", models.CharField(max_length=200, verbose_name="密码")),
                (
                    "default_from_email",
                    models.EmailField(max_length=254, verbose_name="默认发件人"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否为默认配置"),
                ),
                (
                    "timeout",
                    models.IntegerField(default=30, verbose_name="超时时间(秒)"),
                ),
                (
                    "ssl_certfile",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SSL证书文件",
                    ),
                ),
                (
                    "ssl_keyfile",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="SSL密钥文件",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="配置描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "邮件配置",
                "verbose_name_plural": "邮件配置",
                "db_table": "email_configurations",
            },
        ),
    ]
