# Generated by Django 5.2.3 on 2025-06-22 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="子任务标题")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待办"),
                            ("in_progress", "进行中"),
                            ("review", "审核中"),
                            ("done", "已完成"),
                            ("blocked", "已阻塞"),
                        ],
                        default="todo",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="排序位置"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "子任务",
                "verbose_name_plural": "子任务",
                "db_table": "tasks_subtask",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="任务标题",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低优先级"),
                            ("normal", "普通"),
                            ("high", "高优先级"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "待办"),
                            ("in_progress", "进行中"),
                            ("review", "审核中"),
                            ("done", "已完成"),
                            ("blocked", "已阻塞"),
                        ],
                        default="todo",
                        max_length=15,
                        verbose_name="状态",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="排序位置"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="截止日期"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始日期"
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(999.9),
                        ],
                        verbose_name="预估工时",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(999.9),
                        ],
                        verbose_name="实际工时",
                    ),
                ),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="完成进度",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="已归档"),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="模板任务"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks_task",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
            ],
            options={
                "verbose_name": "任务分配",
                "verbose_name_plural": "任务分配",
                "db_table": "tasks_assignment",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="tasks/attachments/", verbose_name="文件"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_size", models.PositiveIntegerField(verbose_name="文件大小")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="文件类型"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=200, null=True, verbose_name="文件描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "任务附件",
                "verbose_name_plural": "任务附件",
                "db_table": "tasks_attachment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="已编辑"),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="编辑时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "任务评论",
                "verbose_name_plural": "任务评论",
                "db_table": "tasks_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("blocks", "阻塞"),
                            ("depends_on", "依赖于"),
                            ("relates_to", "关联"),
                        ],
                        default="depends_on",
                        max_length=15,
                        verbose_name="依赖类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "任务依赖",
                "verbose_name_plural": "任务依赖",
                "db_table": "tasks_dependency",
                "ordering": ["-created_at"],
            },
        ),
    ]
