# Generated by Django 5.2.3 on 2025-06-22 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_initial"),
        ("tasks", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规则名称")),
                ("description", models.TextField(blank=True, verbose_name="规则描述")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("status_change", "状态变更时"),
                            ("task_created", "任务创建时"),
                            ("task_assigned", "任务分配时"),
                            ("due_date_near", "临近截止日期"),
                            ("overdue", "任务逾期时"),
                            ("time_scheduled", "定时触发"),
                        ],
                        max_length=20,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "trigger_conditions",
                    models.JSONField(default=dict, verbose_name="触发条件"),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("change_status", "变更状态"),
                            ("assign_user", "分配用户"),
                            ("move_to_list", "移动到列表"),
                            ("set_priority", "设置优先级"),
                            ("add_label", "添加标签"),
                            ("send_notification", "发送通知"),
                            ("create_subtask", "创建子任务"),
                        ],
                        max_length=20,
                        verbose_name="动作类型",
                    ),
                ),
                (
                    "action_parameters",
                    models.JSONField(default=dict, verbose_name="动作参数"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="规则优先级"),
                ),
                (
                    "max_executions",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="最大执行次数"
                    ),
                ),
                (
                    "execution_count",
                    models.PositiveIntegerField(default=0, verbose_name="已执行次数"),
                ),
                (
                    "schedule_cron",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="定时规则(Cron)"
                    ),
                ),
                (
                    "last_executed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次执行时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_rules",
                        to="boards.board",
                        verbose_name="所属看板",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflow_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流规则",
                "verbose_name_plural": "工作流规则",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowRuleExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=True, verbose_name="执行成功")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "execution_details",
                    models.JSONField(default=dict, verbose_name="执行详情"),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="执行时间"),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="tasks.workflowrule",
                        verbose_name="执行的规则",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_executions",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "规则执行记录",
                "verbose_name_plural": "规则执行记录",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="状态名称")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="显示名称"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d", max_length=7, verbose_name="状态颜色"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="排序位置"),
                ),
                (
                    "is_initial",
                    models.BooleanField(default=False, verbose_name="是否为初始状态"),
                ),
                (
                    "is_final",
                    models.BooleanField(default=False, verbose_name="是否为最终状态"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_statuses",
                        to="boards.board",
                        verbose_name="所属看板",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流状态",
                "verbose_name_plural": "工作流状态",
                "ordering": ["board", "position"],
                "unique_together": {("board", "name"), ("board", "position")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="转换名称")),
                ("description", models.TextField(blank=True, verbose_name="转换描述")),
                (
                    "require_assignee",
                    models.BooleanField(default=False, verbose_name="需要指定受理人"),
                ),
                (
                    "require_comment",
                    models.BooleanField(default=False, verbose_name="需要填写备注"),
                ),
                (
                    "allowed_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允许的角色"
                    ),
                ),
                (
                    "auto_assign_creator",
                    models.BooleanField(default=False, verbose_name="自动分配给创建者"),
                ),
                (
                    "auto_notify_assignees",
                    models.BooleanField(default=True, verbose_name="自动通知受理人"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "auto_move_to_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="boards.boardlist",
                        verbose_name="自动移动到列表",
                    ),
                ),
                (
                    "from_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="tasks.workflowstatus",
                        verbose_name="源状态",
                    ),
                ),
                (
                    "to_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="tasks.workflowstatus",
                        verbose_name="目标状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流转换",
                "verbose_name_plural": "工作流转换",
                "unique_together": {("from_status", "to_status")},
            },
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, max_length=15, verbose_name="原状态"),
                ),
                ("to_status", models.CharField(max_length=15, verbose_name="新状态")),
                ("comment", models.TextField(blank=True, verbose_name="变更备注")),
                (
                    "is_auto_change",
                    models.BooleanField(default=False, verbose_name="是否自动变更"),
                ),
                (
                    "auto_rule_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="自动化规则名称"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="变更时间"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="变更人",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="tasks.task",
                        verbose_name="关联任务",
                    ),
                ),
                (
                    "from_workflow_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="from_history",
                        to="tasks.workflowstatus",
                        verbose_name="原工作流状态",
                    ),
                ),
                (
                    "to_workflow_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="to_history",
                        to="tasks.workflowstatus",
                        verbose_name="新工作流状态",
                    ),
                ),
                (
                    "transition_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tasks.workflowtransition",
                        verbose_name="使用的转换",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务状态历史",
                "verbose_name_plural": "任务状态历史",
                "ordering": ["-created_at"],
            },
        ),
    ]
