# Generated by Django 5.2.3 on 2025-06-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("view", "查看"),
                            ("download", "下载"),
                            ("upload", "上传"),
                            ("share", "分享"),
                            ("invite", "邀请"),
                            ("join", "加入"),
                            ("leave", "离开"),
                            ("comment", "评论"),
                            ("mention", "提及"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="操作描述")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="内容类型"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对象ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="对象表示"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="用户代理"),
                ),
                (
                    "extra_data",
                    models.JSONField(blank=True, default=dict, verbose_name="额外数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "活动日志",
                "verbose_name_plural": "活动日志",
                "db_table": "common_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="uploads/%Y/%m/%d/", verbose_name="文件"
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                ("file_size", models.PositiveIntegerField(verbose_name="文件大小")),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="内容类型"),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="文件哈希"
                    ),
                ),
                (
                    "content_type_related",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="关联内容类型",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="关联对象ID"
                    ),
                ),
                (
                    "is_temporary",
                    models.BooleanField(default=True, verbose_name="临时文件"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开文件"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "文件上传",
                "verbose_name_plural": "文件上传",
                "db_table": "common_file_upload",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "任务分配"),
                            ("task_due", "任务到期"),
                            ("task_completed", "任务完成"),
                            ("comment_added", "新增评论"),
                            ("mention", "被提及"),
                            ("board_invite", "看板邀请"),
                            ("team_invite", "团队邀请"),
                            ("system", "系统通知"),
                        ],
                        max_length=20,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("message", models.TextField(verbose_name="消息内容")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="内容类型"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="对象ID"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="跳转链接"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="已读")),
                ("is_sent", models.BooleanField(default=False, verbose_name="已发送")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="阅读时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "common_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="设置键"
                    ),
                ),
                ("value", models.TextField(verbose_name="设置值")),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("integer", "整数"),
                            ("boolean", "布尔值"),
                            ("json", "JSON"),
                            ("text", "文本"),
                        ],
                        default="string",
                        max_length=10,
                        verbose_name="值类型",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="设置名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="设置描述"),
                ),
                (
                    "category",
                    models.CharField(
                        default="general", max_length=50, verbose_name="分类"
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(default=True, verbose_name="可编辑"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="公开设置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
                "verbose_name_plural": "系统设置",
                "db_table": "common_system_settings",
                "ordering": ["category", "key"],
            },
        ),
    ]
